name: Build x-wrt ZTE-E8820V2

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      
    - name: Set Build Date & Timezone
      run: |
        sudo timedatectl set-timezone "Asia/Jakarta"
        echo "BUILD_DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
        echo "BUILD_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        
    - name: Free Disk Space & Install Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo docker rmi $(docker image ls -q) 2>/dev/null || true
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc
        sudo -E apt-get -y purge azure-cli google-cloud-cli google-chrome-stable firefox powershell dotnet-sdk*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python3-setuptools rsync swig unzip zlib1g-dev file wget binutils bzip2 diff find flex gawk gcc-6+ getopt grep install libc-dev libz-dev
        make4.1+ perl python3.8+ rsync subversion unzip which
        sudo -E apt-get autoremove --purge -y
        sudo -E apt-get clean
        
    - name: Clone x-wrt Source & Checkout Tag
      run: |
        git clone https://github.com/x-wrt/x-wrt.git
        cd x-wrt
        git pull
        git checkout 26.04_b202609161234

    #- name: Cache x-wrt DL and Staging Dir
     # uses: actions/cache@v4
     # with:
       # path: |
       #   x-wrt/dl
       #   x-wrt/staging_dir
        # Cache dikunci berdasarkan versi tag. 
        # Jika Anda mengubah isi file .config Anda, cache akan tetap dipakai (restore), namun jika ada update fungsionalitas, cache akan diperbarui otomatis saat build selesai.
       # key: ${{ runner.os }}-x-wrt-26.04-${{ hashFiles('**/config', '**/.config') }}
       # restore-keys: |
       #   ${{ runner.os }}-x-wrt-26.04-

    - name: Update and Install Feeds
      run: |
        cd x-wrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Fix Squeezelite Recursive Dependency
      run: |
          sed -i 's/+SQUEEZELITE_WMA_ALAC:/@SQUEEZELITE_WMA_ALAC:/g' feeds/packages/sound/squeezelite/Makefile

    - name: Apply Hardmod Fixes (Overwrite DTS & MK)
      run: |
        set -e
        if [ -f "patch-custom/mt7621_zte_e8820v2.dts" ]; then
          cp -f patch-custom/mt7621_zte_e8820v2.dts x-wrt/target/linux/ramips/dts/
          echo "DTS successfully copied!"
        else
          find patch-custom/ -name "*.dts" -exec cp -f {} x-wrt/target/linux/ramips/dts/mt7621_zte_e8820v2.dts \;
          echo "DTS files automatically applied!"
        fi
        
        if [ -f "patch-custom/mt7621.mk" ]; then
          cp -f patch-custom/mt7621.mk x-wrt/target/linux/ramips/image/
          echo "Makefile (mt7621.mk) successfully replaced!"
        fi
        
        if [ -f "patch-custom/01_leds" ]; then
          cp -f patch-custom/01_leds x-wrt/target/linux/ramips/mt7621/base-files/etc/board.d/
          echo "Makefile (01_leds) successfully replaced!"
        fi

        if [ -f "patch-custom/02_network" ]; then
          cp -f patch-custom/02_network x-wrt/target/linux/ramips/mt7621/base-files/etc/board.d/
          echo "Makefile (02_network) successfully replaced!"
        fi
          
    - name: Generate Config file
      run: |
        cd x-wrt
        if [ -f "../.config" ]; then
          cp -f ../.config .config
          echo "Berhasil menyalin .config kustom!"
        else
          echo "CONFIG_TARGET_ramips=y" > .config
          echo "CONFIG_TARGET_ramips_mt7621=y" >> .config
          echo "CONFIG_TARGET_ramips_mt7621_DEVICE_mt7621_zte_e8820v2=y" >> .config
        fi
        
        make defconfig
        
    - name: Download Package Source (Pre-download)
      run: |
        cd x-wrt
        make download -j$(nproc)
        find dl -size 0 -exec rm -f {} \;
        
    - name: Compile Toolchain & Firmware (World)
      run: |
        cd x-wrt
        make -j$(nproc) world || make -j1 V=s world

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: x-wrt_26.04_ZTE_E8820v2_${{ env.BUILD_DATE }}
        path: x-wrt/bin
